// Generated by CoffeeScript 1.8.0
(function() {


}).call(this);

//# sourceMappingURL=another.js.map

// Generated by CoffeeScript 1.8.0
(function() {
  var a, add, b, c;

  a = 1;

  b = 2;

  c = 3;

  add = function() {
    return a * b * c;
  };

}).call(this);

//# sourceMappingURL=popups.js.map
